/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import dominio.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnoFI
 */
public class BajaPostulanteJDialog extends javax.swing.JDialog {

    private Postulante modelo;
    private Sistema sistema;
    private Postulante post;

    public BajaPostulanteJDialog (java.awt.Frame parent, boolean modal, Sistema unS) {
        super(parent, modal);
        sistema = unS;
        //this.modelo = modelo;
        this.sistema = unS;
        this.setResizable(false);
        initComponents();
        ArrayList<Postulante> postul = sistema.getPostulantes();
        ArrayList<String> cedulas = new ArrayList<>();
        for (int i = 0; i < postul.size(); i++) {
            cedulas.add(postul.get(i).getCedula());
        }

        String[] postulantes = new String[postul.size()];
        for (int i = 0; i < postulantes.length; i++) {
            postulantes[i] = "Nombre: " + postul.get(i).getNombre() + ". Cédula: " + cedulas.get(i);
        }

        jListBaja.setListData(postulantes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabelSubTitulo = new javax.swing.JLabel();
        jBtbCancelar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBaja = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setText("Dar de baja ");

        jLabelSubTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSubTitulo.setText("En esta ventana podrá dar de baja a los postulantes anteriormente registrados.");

        jBtbCancelar.setText("Cancelar");
        jBtbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtbCancelarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jListBaja.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListBaja);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSubTitulo)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnEliminar)
                        .addGap(75, 75, 75))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(27, 27, 27)
                .addComponent(jLabelSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtbCancelar)
                    .addComponent(jBtnEliminar))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtbCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtbCancelarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        if (!jListBaja.isSelectionEmpty()) {
            String postSelect = jListBaja.getSelectedValue();
            String nomPostSel = postSelect.substring(8, postSelect.indexOf("."));
            System.out.println("postulante a borrar " + nomPostSel);
            ArrayList<Postulante> listaPostul = sistema.getPostulantes();     //nomPostSel.getConocimiento();
            boolean bandeira = false;
            for (int i = 0; i < listaPostul.size() && !bandeira; i++) {
                if (listaPostul.get(i).getNombre().equals(nomPostSel)) {
                    listaPostul.remove(listaPostul.get(i));
                    System.out.println("bom dia del bandeira");
                    bandeira = true;
                }
            }

            //int nivel = (int) spinnerNivel.getValue();
            //ArrayList<Tematica> temas = modeloPost.getConocimiento();
            ArrayList<Postulante> postul = sistema.getPostulantes();
            ArrayList<String> cedulas = new ArrayList<>();
            for (int i = 0; i < postul.size(); i++) {
                cedulas.add(postul.get(i).getCedula());
            }

            String[] postulantes = new String[postul.size()];
            for (int i = 0; i < postulantes.length; i++) {
                postulantes[i] = "Nombre: " + postul.get(i).getNombre() + ". Cédula: " + cedulas.get(i);
            }

            jListBaja.setListData(postulantes);
        } else {
            JOptionPane.showMessageDialog(this, "No seleccionó ningún postulante.");
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtbCancelar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JLabel jLabelSubTitulo;
    private javax.swing.JList<String> jListBaja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
