
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
//Matías Ohanian 305720 && Valentino Barreiro 308473 
package interfaz;

import dominio.*;
import java.util.*;

public class ConsultaTematicaJDialog extends javax.swing.JDialog {

    private Sistema sistema;

    public ConsultaTematicaJDialog (java.awt.Frame parent, boolean modal, Sistema sistema) {
        super(parent, modal);
        this.sistema = sistema;
        initComponents();
        this.setResizable(false);

        ArrayList<Tematica> tema = new ArrayList<>();
        tema = this.sistema.getTematicas();

        String[] tematica = new String[tema.size()];
        for (int i = 0; i < tematica.length; i++) {
            tematica[i] = "" + tema.get(i).getNombre();
        }
        lstTemas.setListData(tematica);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTemas = new javax.swing.JList<>();
        lblSeleccionar = new javax.swing.JLabel();
        lblCantMayor5 = new javax.swing.JLabel();
        lblCantPuestos = new javax.swing.JLabel();
        lblRespMayor5 = new javax.swing.JLabel();
        lblRespCantTema = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Estadísticas según temática");

        lstTemas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTemas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTemasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstTemas);

        lblSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSeleccionar.setText("Seleccionar una tematica:");

        lblCantMayor5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantMayor5.setText("Cantidad de postulantes con nivel mayor a 5:");

        lblCantPuestos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantPuestos.setText("Cantidad de puestos con la tematica seleccionada: ");

        lblRespMayor5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRespCantTema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantMayor5)
                            .addComponent(lblCantPuestos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRespMayor5, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(lblRespCantTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSeleccionar)
                        .addGap(133, 133, 133))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantMayor5)
                    .addComponent(lblRespMayor5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantPuestos)
                    .addComponent(lblRespCantTema))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstTemasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTemasValueChanged
        ArrayList<Tematica> temas = sistema.getTematicas();
        ArrayList<Postulante> todosPost = sistema.getPostulantes();
        ArrayList<Puesto> todosPuestos = sistema.getPuestos();
        int index = lstTemas.getAnchorSelectionIndex();
        int cantidadPost = 0;
        int cantPorTema = 0;
        if (todosPost.isEmpty()) {
            lblRespMayor5.setText("Sin postulantes.");
        } else {
            for (int i = 0; i < todosPost.size(); i++) {

                for (int j = 0; j < todosPost.get(i).getConocimiento().size(); j++) {

                    int nivelPost = todosPost.get(i).getNiveles().get(j);
                    String tematicaPost = todosPost.get(i).getConocimiento().get(j).getNombre();

                    if (temas.get(index).getNombre().equals(tematicaPost) && nivelPost > 5) {
                        cantidadPost++;
                    } else {
                        lblRespMayor5.setText("Sin postulantes.");
                    }
                }
            }
        }
        if (todosPuestos.isEmpty()) {
            lblRespCantTema.setText("Sin puestos.");
        } else {
            for (int j = 0; j < todosPuestos.size(); j++) {
                if (todosPuestos.get(j).getTemasRequeridos().contains(temas.get(index))) {
                    cantPorTema++;
                } else {
                    lblRespCantTema.setText("Sin puestos.");
                }
            }
        }

        if (cantPorTema > 0) {
            lblRespCantTema.setText(cantPorTema + "");
        }
        if (cantidadPost > 0) {
            lblRespMayor5.setText("" + cantidadPost);
        }
    }//GEN-LAST:event_lstTemasValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCantMayor5;
    private javax.swing.JLabel lblCantPuestos;
    private javax.swing.JLabel lblRespCantTema;
    private javax.swing.JLabel lblRespMayor5;
    private javax.swing.JLabel lblSeleccionar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstTemas;
    // End of variables declaration//GEN-END:variables
}
