package interfaz;

import dominio.*;
import java.util.*;
import javax.swing.JOptionPane;

public class IngresoEntrevistaJDialog extends javax.swing.JDialog {

    private Sistema sistema;
    private Entrevista entrevista;
    private Postulante postulante;

    public IngresoEntrevistaJDialog (java.awt.Frame parent, boolean modal, Sistema unS) {
        super(parent, modal);
        sistema = unS;
        initComponents();
        this.setResizable(false);
        ArrayList<Evaluador> evaluador = new ArrayList<>();

        evaluador = sistema.getEvaluadores();

        String[] evaluadores = new String[evaluador.size()];
        for (int i = 0; i < evaluadores.length; i++) {
            evaluadores[i] = "" + evaluador.get(i).getNombre();
        }
        jListEval.setListData(evaluadores);

        ArrayList<Postulante> postulantes = new ArrayList<>();

        postulantes = sistema.getPostulantes();

        String[] postulados = new String[postulantes.size()];
        for (int i = 0; i < postulados.length; i++) {
            postulados[i] = "" + postulantes.get(i).getNombre();
        }
        jListPost.setListData(postulados);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEval = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPost = new javax.swing.JList<>();
        jLabelEvals = new javax.swing.JLabel();
        jLabelPost = new javax.swing.JLabel();
        jLabelSubTit = new javax.swing.JLabel();
        jLabelPuntaje = new javax.swing.JLabel();
        jSpinnerPuntaje = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaComent = new javax.swing.JTextArea();
        jLabelComent = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnIngreso = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setText("Ingresar entrevista");

        jScrollPane1.setViewportView(jListEval);

        jScrollPane2.setViewportView(jListPost);

        jLabelEvals.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEvals.setText("Evaluadores:");

        jLabelPost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPost.setText("Postulantes:");

        jLabelSubTit.setText("Seleccione al evaluador y al postulante, luego deje un puntaje y comentario.");

        jLabelPuntaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPuntaje.setText("Puntaje:");

        jSpinnerPuntaje.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jTextAreaComent.setColumns(20);
        jTextAreaComent.setRows(5);
        jScrollPane3.setViewportView(jTextAreaComent);

        jLabelComent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelComent.setText("Comentario:");

        jbtnIngreso.setText("Ingresar");
        jbtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresoActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelTitulo)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelEvals)
                                    .addGap(119, 119, 119)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPuntaje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPost)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelComent)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnIngreso)
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelSubTit)
                        .addGap(8, 8, 8)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(23, 23, 23)
                .addComponent(jLabelSubTit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelEvals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPuntaje)
                    .addComponent(jSpinnerPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIngreso)
                    .addComponent(jbtnCancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresoActionPerformed
        if (!chequeo()) {
            JOptionPane.showMessageDialog(this, "No se logró agregar entrevista.");
        } else {
            this.entrevista = new Entrevista();
            
            
            String nombreEval = jListEval.getSelectedValue();
            Evaluador evalSelected;
            boolean hecho = false;
            for (int i = 0; i < sistema.getEvaluadores().size() && !hecho; i++) {
                if (nombreEval.equals(sistema.getEvaluadores().get(i).getNombre())) {
                    evalSelected = sistema.getEvaluadores().get(i);
                    entrevista.setEvaluador(evalSelected);
                    hecho = true;
                }

            }
            
            String nombrePost = jListPost.getSelectedValue();
            Postulante postSelected = new Postulante();
            hecho = false;
            for (int i = 0; i < sistema.getSizePostulantes() && !hecho; i++) {
                if (nombrePost.equals(sistema.getPostulantes().get(i).getNombre())) {
                    postSelected = sistema.getPostulantes().get(i);
                    entrevista.setPostulante(postSelected);
                    hecho = true;
                }
            }
            entrevista.setPuntaje((int) jSpinnerPuntaje.getValue());
            entrevista.setDescripcion(jTextAreaComent.getText());
            sistema.addEntrevista(entrevista);
            postSelected.addEntrevista(entrevista);
            this.dispose();
        }
    }//GEN-LAST:event_jbtnIngresoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelComent;
    private javax.swing.JLabel jLabelEvals;
    private javax.swing.JLabel jLabelPost;
    private javax.swing.JLabel jLabelPuntaje;
    private javax.swing.JLabel jLabelSubTit;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListEval;
    private javax.swing.JList<String> jListPost;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerPuntaje;
    private javax.swing.JTextArea jTextAreaComent;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnIngreso;
    // End of variables declaration//GEN-END:variables
    public boolean chequeo () {
        boolean flag = true;
        if (jTextAreaComent.getText().isBlank()) {
            flag = false;
        } else {
            if ((int) jSpinnerPuntaje.getValue() > 100 || (int) jSpinnerPuntaje.getValue() < 0) {
                flag = false;
            } else {
                if (jListEval.isSelectionEmpty()) {
                    flag = false;
                } else {
                    if (jListPost.isSelectionEmpty()) {
                        flag = false;
                    }
                }
            }
        }
        return flag;
    }

}
