package interfaz;

import dominio.Postulante;
import dominio.*;
import dominio.Verficador;
import java.awt.*;
import javax.print.attribute.AttributeSetUtilities;
import javax.swing.*;

public class PostulanteJDialogue extends javax.swing.JDialog {

    Postulante modelo = new Postulante();
    //Sistema sist = new Sistema();
    public PostulanteJDialogue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGupo = new javax.swing.ButtonGroup();
        lblAltaPost = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblDir = new javax.swing.JLabel();
        lblTelf = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        lblFormato = new javax.swing.JLabel();
        rbtnRemoto = new javax.swing.JRadioButton();
        rbtnPresencial = new javax.swing.JRadioButton();
        rbtnMixto = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAltaPost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAltaPost.setText("Alta Postulante");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCedula.setText("Cédula:");

        lblDir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDir.setText("Dirección:");

        lblTelf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelf.setText("Teléfono:");

        lblMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMail.setText("Mail:");

        lblLinkedin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLinkedin.setText("Linkedin:");

        txtNombre.setNextFocusableComponent(txtCedula);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtCedula.setForeground(new java.awt.Color(204, 204, 204));
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setCaretColor(new java.awt.Color(153, 153, 153));
        txtCedula.setInputVerifier(new Verficador());
        txtCedula.setNextFocusableComponent(txtDireccion);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        txtDireccion.setNextFocusableComponent(txtTelefono);

        txtTelefono.setInputVerifier(new Verficador());
        txtTelefono.setNextFocusableComponent(txtMail);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtMail.setNextFocusableComponent(txtLinkedin);
        txtMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailFocusLost(evt);
            }
        });
        txtMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                none(evt);
            }
        });
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });
        txtMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nose(evt);
            }
        });

        txtLinkedin.setNextFocusableComponent(rbtnRemoto);
        txtLinkedin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLinkedinFocusLost(evt);
            }
        });
        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        lblFormato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFormato.setText("Formato:");

        btnGupo.add(rbtnRemoto);
        rbtnRemoto.setSelected(true);
        rbtnRemoto.setText("Remoto");
        rbtnRemoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbtnRemoto.setNextFocusableComponent(btnCancelar);
        rbtnRemoto.setRequestFocusEnabled(false);
        rbtnRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRemotoActionPerformed(evt);
            }
        });

        btnGupo.add(rbtnPresencial);
        rbtnPresencial.setText("Presencial");
        rbtnPresencial.setNextFocusableComponent(btnCancelar);
        rbtnPresencial.setRequestFocusEnabled(false);

        btnGupo.add(rbtnMixto);
        rbtnMixto.setText("Mixto");
        rbtnMixto.setFocusTraversalPolicyProvider(true);
        rbtnMixto.setNextFocusableComponent(btnCancelar);
        rbtnMixto.setRequestFocusEnabled(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.setNextFocusableComponent(btnSig);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSig.setText("Siguiente");
        btnSig.setMaximumSize(new java.awt.Dimension(80, 27));
        btnSig.setMinimumSize(new java.awt.Dimension(80, 27));
        btnSig.setNextFocusableComponent(txtNombre);
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(lblAltaPost)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblDir)
                            .addComponent(lblTelf)
                            .addComponent(lblMail)
                            .addComponent(lblLinkedin)
                            .addComponent(lblFormato)
                            .addComponent(lblCedula))
                        .addGap(90, 90, 90)
                        .addComponent(rbtnRemoto)
                        .addGap(32, 32, 32)
                        .addComponent(rbtnPresencial)
                        .addGap(32, 32, 32)
                        .addComponent(rbtnMixto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtCedula)
                            .addComponent(txtDireccion)
                            .addComponent(txtTelefono)
                            .addComponent(txtMail)
                            .addComponent(txtLinkedin)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSig, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAltaPost)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDir)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelf)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMail)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormato)
                    .addComponent(rbtnRemoto)
                    .addComponent(rbtnPresencial)
                    .addComponent(rbtnMixto))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSig, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void rbtnRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRemotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRemotoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        if (!(esMail(txtMail.getText())) || !(txtLinkedin.getText().contains("https://linkedin.com/in/")) ) {
            //JOptionPane.showMessageDialog(this, "No es un mail válido");
            txtMail.requestFocusInWindow();
            txtLinkedin.requestFocusInWindow();
            
        } else {
            String nombre = txtNombre.getText();
            String cedula = txtCedula.getText();
            String direccion = txtDireccion.getText();
            String mail = txtMail.getText();
            String linkedin = txtLinkedin.getText();
            
               
            
            modelo.setLinkedIn(linkedin);
            

            String modalidad;
            if (rbtnMixto.isSelected()) {
                modalidad = rbtnMixto.getText();
            } else {
                if (rbtnPresencial.isSelected()) {
                    modalidad = rbtnPresencial.getText();
                } else {
                    modalidad = rbtnRemoto.getText();
                }
            }
            System.out.println(modalidad);

            modelo.setNombre(nombre);
            modelo.setCedula(cedula);
            modelo.setDireccion(direccion);
            modelo.setMail(mail);
            

            ExperienciaJDialogue ventanita = new ExperienciaJDialogue(new JFrame(), true, modelo);
            ventanita.setVisible(true);
            modelo = ventanita.darP();
            //sist.addPostulantes(modelo);
            
        }   
    }//GEN-LAST:event_btnSigActionPerformed
    
    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        if (!(esNumero(txtCedula.getText())) || txtCedula.getText().length() < 7) {
            txtCedula.setForeground(new Color(250, 0, 0));
        } else {
            txtCedula.setForeground(new Color(0, 0, 0));
        }
        //System.out.println("soy ese");
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed

    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        if (!(esNumero(txtTelefono.getText()))) {
            txtTelefono.setForeground(new Color(250, 0, 0));
        } else {
            txtTelefono.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed

    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void nose(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nose
        /*if(!(txtMail.getText().contains("@gmail.com"))){
            JOptionPane.showMessageDialog(this, "No es un mail válido");
        }*/
    }//GEN-LAST:event_nose

    private void none(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_none

    }//GEN-LAST:event_none

    private void txtMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailFocusLost
        if (!(esMail(txtMail.getText()))) {
            JOptionPane.showMessageDialog(this, "No es un mail válido");
            txtMail.requestFocusInWindow();
        }

    }//GEN-LAST:event_txtMailFocusLost

    private void txtLinkedinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedinFocusLost
        if (!(txtLinkedin.getText().contains("https://linkedin.com/in/"))) {
            JOptionPane.showMessageDialog(this, "No es un Linkedin válido");
            txtLinkedin.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtLinkedinFocusLost
    public static boolean esMail(String unN) {
        boolean retorno = false;
        if (unN.contains("@gmail.com")) {
            retorno = true;
        }
        return retorno;
    }

    public static boolean esNumero(String unS) {
        boolean esN = true;

        for (int i = 0; i < unS.length() && esN; i++) {
            char aux = unS.charAt(i);

            if (!Character.isDigit(aux)) {
                esN = false;
            }
        }

        return esN && (unS.length() > 0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGupo;
    private javax.swing.JButton btnSig;
    private javax.swing.JLabel lblAltaPost;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelf;
    private javax.swing.JRadioButton rbtnMixto;
    private javax.swing.JRadioButton rbtnPresencial;
    private javax.swing.JRadioButton rbtnRemoto;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public String radioBotonSeleccionado() {
        String retorno;
        if (rbtnRemoto.isSelected()) {
            retorno = rbtnRemoto.getName();
        } else {
            if (rbtnPresencial.isSelected()) {
                retorno = rbtnPresencial.getName();
            } else {
                retorno = rbtnMixto.getName();
            }
        }
        return retorno;
    }
    public Postulante devolverPost (){
        return this.modelo;
    }

}
