
package interfaz;

import dominio.*;


public class Principal extends javax.swing.JFrame {

    private Sistema modelo; 
    
    public Principal(Sistema sistema) {
        this.setResizable(false);
        this.modelo = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGestion = new javax.swing.JLabel();
        btnTematica = new javax.swing.JButton();
        btnPostularme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa para la gestión de postulantes");

        lblGestion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGestion.setText("Gestión de Personal");

        btnTematica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTematica.setText("Registrar Temática");
        btnTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTematicaActionPerformed(evt);
            }
        });

        btnPostularme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPostularme.setText("Postularme");
        btnPostularme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostularmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblGestion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnPostularme, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPostularme, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTematicaActionPerformed
        TematicaJDialogue ventanita = new TematicaJDialogue(this, true, modelo);
        ventanita.setVisible(true);
        Tematica modeloFin = new Tematica();
        modeloFin = ventanita.devolverTem();
        modelo.addTematicas(modeloFin);
    }//GEN-LAST:event_btnTematicaActionPerformed

    private void btnPostularmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostularmeActionPerformed
        PostulanteJDialogue vent = new PostulanteJDialogue(this, true, modelo);
        vent.setVisible(true);
        Postulante modeloFin = new Postulante();
        modeloFin = vent.devolverPost();
        modelo.addPostulantes(modeloFin);
    }//GEN-LAST:event_btnPostularmeActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPostularme;
    private javax.swing.JButton btnTematica;
    private javax.swing.JLabel lblGestion;
    // End of variables declaration//GEN-END:variables
}
