//Matías Ohanian 305720 && Valentino Barreiro 308473 
package interfaz;

import dominio.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class RegistroEvaluadorJDialog extends javax.swing.JDialog {

    private Sistema sistema;
    private Postulante post;
    private Evaluador eval;

    public RegistroEvaluadorJDialog (java.awt.Frame parent, boolean modal, Sistema unS) {
        super(parent, modal);
        this.setResizable(false);
        sistema = unS;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelDir = new javax.swing.JLabel();
        jLabelIngreso = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldCed = new javax.swing.JTextField();
        jTextFieldDir = new javax.swing.JTextField();
        jTextFieldIngreso = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblAdvertNomb = new javax.swing.JLabel();
        lblAdvertCedula = new javax.swing.JLabel();
        lblAdvertDirec = new javax.swing.JLabel();
        lblAdvertRango = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblTitulo.setText("Registrar Evaluador");

        jLabelNom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNom.setText("Nombre:");

        jLabelCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCedula.setText("Cédula:");

        jLabelDir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDir.setText("Dirección:");

        jLabelIngreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelIngreso.setText("Año de Ingreso:");

        jButtonCancel.setText("Cancelar");
        jButtonCancel.setToolTipText("");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setToolTipText("Registrar al evaluador.");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });
        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyReleased(evt);
            }
        });

        jTextFieldCed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCedKeyReleased(evt);
            }
        });

        jTextFieldDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDirKeyReleased(evt);
            }
        });

        lblAdvertNomb.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblAdvertNomb.setText("Campo obligatorio.");

        lblAdvertCedula.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblAdvertCedula.setText("La cédula es incorrecta.");

        lblAdvertDirec.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblAdvertDirec.setText("Dirección vacía.");

        lblAdvertRango.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblAdvertRango.setText("Rango: 1960 - Act.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCancel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCedula)
                        .addComponent(jLabelNom)
                        .addComponent(jLabelDir)
                        .addComponent(jLabelIngreso)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrar)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDir)
                            .addComponent(jTextFieldCed)
                            .addComponent(jTextFieldNom)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdvertNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdvertCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdvertDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdvertRango, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLblTitulo)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdvertNomb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula)
                    .addComponent(jTextFieldCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdvertCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDir)
                    .addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdvertDirec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIngreso)
                    .addComponent(jTextFieldIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblAdvertRango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonRegistrar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        this.eval = new Evaluador();

        if (!chequeo()) {
            JOptionPane.showMessageDialog(this, "No fue posible crear al evaluador. Revisar datos ingresados.");
        } else {

            String nomb = jTextFieldNom.getText();
            String cedula = jTextFieldCed.getText();
            String dirrec = jTextFieldDir.getText();
            int ingreso = Integer.parseInt(jTextFieldIngreso.getText());

            eval.setNombre(nomb);
            eval.setCedula(cedula);
            eval.setAnoIngreso(ingreso);
            eval.setDireccion(dirrec);

            sistema.addEvaluador(this.eval);
            this.setVisible(false);
        }


    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyReleased
        if (jTextFieldNom.getText().isBlank()) {
            lblAdvertNomb.setText("Campo obligatorio.");
        } else {
            lblAdvertNomb.setText(" ");
        }
    }//GEN-LAST:event_jTextFieldNomKeyReleased

    private void jTextFieldCedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCedKeyReleased
        if (jTextFieldCed.getText().isBlank() && !esCedula(jTextFieldCed.getText())) {
            lblAdvertCedula.setText("La cédula es incorrecta.");
        } else {
            lblAdvertCedula.setText(" ");
        }
    }//GEN-LAST:event_jTextFieldCedKeyReleased

    private void jTextFieldDirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDirKeyReleased

        if (jTextFieldDir.getText().isBlank()) {
            lblAdvertDirec.setText("Dirección vacía.");
        } else {
            lblAdvertDirec.setText(" ");
        }
    }//GEN-LAST:event_jTextFieldDirKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelDir;
    private javax.swing.JLabel jLabelIngreso;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCed;
    private javax.swing.JTextField jTextFieldDir;
    private javax.swing.JTextField jTextFieldIngreso;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JLabel lblAdvertCedula;
    private javax.swing.JLabel lblAdvertDirec;
    private javax.swing.JLabel lblAdvertNomb;
    private javax.swing.JLabel lblAdvertRango;
    // End of variables declaration//GEN-END:variables
    public boolean chequeo () {
        boolean bien = true;
        if (jTextFieldNom.getText().isBlank()) {
            bien = false;
        } else {
            int cedula;
            try {
                cedula = Integer.parseInt(jTextFieldCed.getText());
            } catch (NumberFormatException e) {
                e.getMessage();
                return false;
            }
            if (jTextFieldCed.getText().isBlank()) {
                bien = false;
            } else {
                if (jTextFieldDir.getText().isBlank()) {
                    bien = false;
                } else {
                    int ingreso = 0;
                    try {
                        ingreso = Integer.parseInt(jTextFieldIngreso.getText());
                    } catch (NumberFormatException e) {
                        e.getMessage();

                    }
                    if (jTextFieldIngreso.getText().isBlank() || ingreso > 2023 || ingreso < 1960) {
                        bien = false;
                    }
                }
            }
        }
        for (int i = 0; i < sistema.getSizeEvaluador(); i++) {
            if (jTextFieldCed.getText().equals(sistema.getEvaluadores().get(i).getCedula())) {
                bien = false;
            }
        }
        return bien;
    }

    public boolean esCedula (String unaC) {
        boolean bien = true;
        int cedula;
        try {
            cedula = Integer.parseInt(unaC);
        } catch (NumberFormatException e) {
            e.getMessage();
            return false;
        }
        return bien;
    }

}
